### ISSUE TITLE
SMT clones but iOSified in a better way?

### ISSUE THREAD

**Issue by heckarman** [Goodwy/Goodwy-Commons#9]
Hey, goodwy, long time user of your apps. Lately, I was looking at your source code so that I can make some improvements, at least for my personal use and learnt that, all of your apps are based out of SimpleMobileTools (Gallery, Dialer, Contacts, Message, and Commons prominently). I understand that you built on top of tibbi's work. But not giving any credits to the original developer seems not right for the most part. Again, I've no affiliations with him nor do I ask you to give him the credits (would be great if you did).  
All that I wanted to learn here is that, how can the apps be made better, more polished, perfect app or daily usage. 

I've been searching for Contacts, Dialer, and Gallery alternatives for longer period of time and partially, I'm satisfied with your version of apps. I would want to know:
- Are there any plans of doing releases on GitHub, providing build instructions (given that your version of apps are reproducible)?
- Are you planning to bring in some major changes that would actually make the apps more usable for day to day life rather than sticking around with Google's version of apps?

Please do put up road maps and let the OSS community know if there are more contributors required as it would help gain more visibility.

**Comment by Goodwy** [comment]
Hey, these applications are based on SMT, but have big differences not only visual, but also internal (fixed bugs found, added features).
This project is my hobby and is not my main job, so I develop it to the best of my ability without having a plan. All applications are reproducible as well as SMT. I don't mind copying, forking and will be glad to any help. 
I'll try to put the actual releases on GitHub this month, but it will most likely be a regular Google Play version. I don't want to support multiple versions at the same time, which is why there is no FOSS version out yet. You can unlock the Google Play version now for free if you don't have Google Play on your device.

**Comment by heckarman** [comment]
Glad to know but I never thought there would be differences under the hood in terms of working of the app (I started with translations, a bit of code review and nothing much).  
Would love to contribute in my free time.
